name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm test

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-build
        path: dist/liga-hedvig

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v2
      with:
        name: production-build
        path: ./dist

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: liga-hedvig
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./dist/liga-hedvig
